// app.js — NovaSphere demo i18n scaffold, now wired to the context engine (Phase 3).
//
// The dictionary also carries weather/holiday label translations so
// integration.js can render them without a second i18n system. Manual
// language changes always win over auto-detection — see `manualOverride`
// and `setLanguageFromContext` below, which integration.js calls.
(() => {
  const translations = {
    en: {
      nav_features: "Features",
      nav_pricing: "Pricing",
      nav_cta: "Get Started",
      hero_title: "The operating system for teams that move fast",
      hero_sub: "Plan, automate, and ship together — one workspace, no busywork.",
      hero_note: "No credit card required · Cancel anytime",
      cta_primary: "Start free trial",
      features_title: "Everything your team needs, in one place",
      feature_1_title: "Unified workspace",
      feature_1_desc: "Tasks, chat, and roadmaps in one shared space — no more switching between five tools.",
      feature_2_title: "Automation & AI assist",
      feature_2_desc: "Smart workflows learn how your team works and take the repetitive tasks off your plate.",
      feature_3_title: "Secure by design",
      feature_3_desc: "SOC 2 and ISO-aligned controls with granular, role-based access — built in, not bolted on.",
      pricing_title: "Simple pricing that scales with you",
      pricing_sub: "No surprise charges. Cancel anytime.",
      pricing_basic_title: "Starter",
      pricing_basic_feature1: "Up to 5 users",
      pricing_basic_feature2: "Core features",
      pricing_basic_feature3: "Email support",
      pricing_pro_badge: "Most popular",
      pricing_pro_title: "Pro",
      pricing_pro_feature1: "Everything in Starter",
      pricing_pro_feature2: "Advanced automation",
      pricing_pro_feature3: "Priority support",
      pricing_getstarted: "Get started",
      pricing_enterprise_title: "Enterprise",
      pricing_enterprise_price: "Custom pricing",
      pricing_enterprise_feature1: "Unlimited users",
      pricing_enterprise_feature2: "Dedicated success manager",
      pricing_enterprise_feature3: "SSO & custom contracts",
      pricing_enterprise_feature4: "24/7 priority support",
      pricing_contact: "Contact sales",
      footer_tagline: "The operating system for teams that move fast.",
      footer_link_pricing: "Pricing",
      footer_link_privacy: "Privacy",
      footer_link_terms: "Terms",
      footer_link_contact: "Contact",
      footer_rights: "All rights reserved.",
      year: "", // will be replaced by current year
      // Weather labels (keyed to context-engine.js WEATHER_CODES / weather-themes.js labelKey)
      weather_clear: "Clear sky", weather_mostly_clear: "Mostly clear", weather_partly_cloudy: "Partly cloudy",
      weather_cloudy: "Cloudy", weather_fog: "Fog", weather_fog_rime: "Rime fog",
      weather_drizzle_light: "Light drizzle", weather_drizzle_moderate: "Drizzle", weather_drizzle_dense: "Dense drizzle",
      weather_freezing_drizzle_light: "Light freezing drizzle", weather_freezing_drizzle_dense: "Freezing drizzle",
      weather_rain_light: "Light rain", weather_rain_moderate: "Rain", weather_rain_heavy: "Heavy rain",
      weather_freezing_rain_light: "Light freezing rain", weather_freezing_rain_heavy: "Freezing rain",
      weather_snow_light: "Light snow", weather_snow_moderate: "Snow", weather_snow_heavy: "Heavy snow",
      weather_snow_grains: "Snow grains", weather_rain_showers_light: "Light showers",
      weather_rain_showers_moderate: "Showers", weather_rain_showers_violent: "Violent showers",
      weather_snow_showers_light: "Light snow showers", weather_snow_showers_heavy: "Heavy snow showers",
      weather_thunderstorm: "Thunderstorm", weather_thunderstorm_hail_light: "Thunderstorm with light hail",
      weather_thunderstorm_hail_heavy: "Thunderstorm with heavy hail", weather_unknown: "Weather unavailable",
      // Widget & holiday banner
      widget_weather_label: "Right now in {city}",
      widget_updated_label: "Updated",
      holiday_banner_template: "Happy holiday! Today is a public holiday in {country}.",
      geo_consent_prompt: "Allow precise location for more accurate local weather?",
      geo_consent_note: "The site works fine without it — precise location is only used for local weather.",
      geo_consent_allow: "Allow",
      geo_consent_deny: "No thanks",
    },
    es: {
      nav_features: "Funciones",
      nav_pricing: "Precios",
      nav_cta: "Comenzar",
      hero_title: "El sistema operativo para equipos que avanzan rápido",
      hero_sub: "Planifica, automatiza y lanza en equipo — un solo espacio, sin tareas repetitivas.",
      hero_note: "Sin tarjeta de crédito · Cancela cuando quieras",
      cta_primary: "Iniciar prueba gratuita",
      features_title: "Todo lo que tu equipo necesita, en un solo lugar",
      feature_1_title: "Espacio de trabajo unificado",
      feature_1_desc: "Tareas, chat y hojas de ruta en un solo lugar — sin saltar entre cinco herramientas.",
      feature_2_title: "Automatización e IA",
      feature_2_desc: "Flujos inteligentes que aprenden cómo trabaja tu equipo y eliminan las tareas repetitivas.",
      feature_3_title: "Seguridad desde el diseño",
      feature_3_desc: "Controles alineados con SOC 2 e ISO, con acceso granular basado en roles.",
      pricing_title: "Precios simples que escalan contigo",
      pricing_sub: "Sin sorpresas. Cancela cuando quieras.",
      pricing_basic_title: "Inicio",
      pricing_basic_feature1: "Hasta 5 usuarios",
      pricing_basic_feature2: "Funciones básicas",
      pricing_basic_feature3: "Soporte por correo",
      pricing_pro_badge: "Más popular",
      pricing_pro_title: "Pro",
      pricing_pro_feature1: "Todo lo de Inicio",
      pricing_pro_feature2: "Automatización avanzada",
      pricing_pro_feature3: "Soporte prioritario",
      pricing_getstarted: "Empezar",
      pricing_enterprise_title: "Empresarial",
      pricing_enterprise_price: "Precio a medida",
      pricing_enterprise_feature1: "Usuarios ilimitados",
      pricing_enterprise_feature2: "Gestor de éxito dedicado",
      pricing_enterprise_feature3: "SSO y contratos personalizados",
      pricing_enterprise_feature4: "Soporte prioritario 24/7",
      pricing_contact: "Contactar ventas",
      footer_tagline: "El sistema operativo para equipos que avanzan rápido.",
      footer_link_pricing: "Precios",
      footer_link_privacy: "Privacidad",
      footer_link_terms: "Términos",
      footer_link_contact: "Contacto",
      footer_rights: "Todos los derechos reservados.",
      year: "",
      weather_clear: "Cielo despejado", weather_mostly_clear: "Mayormente despejado", weather_partly_cloudy: "Parcialmente nublado",
      weather_cloudy: "Nublado", weather_fog: "Niebla", weather_fog_rime: "Niebla helada",
      weather_drizzle_light: "Llovizna ligera", weather_drizzle_moderate: "Llovizna", weather_drizzle_dense: "Llovizna densa",
      weather_freezing_drizzle_light: "Llovizna helada ligera", weather_freezing_drizzle_dense: "Llovizna helada",
      weather_rain_light: "Lluvia ligera", weather_rain_moderate: "Lluvia", weather_rain_heavy: "Lluvia intensa",
      weather_freezing_rain_light: "Lluvia helada ligera", weather_freezing_rain_heavy: "Lluvia helada",
      weather_snow_light: "Nieve ligera", weather_snow_moderate: "Nieve", weather_snow_heavy: "Nieve intensa",
      weather_snow_grains: "Granos de nieve", weather_rain_showers_light: "Chubascos ligeros",
      weather_rain_showers_moderate: "Chubascos", weather_rain_showers_violent: "Chubascos violentos",
      weather_snow_showers_light: "Chubascos de nieve ligeros", weather_snow_showers_heavy: "Chubascos de nieve intensos",
      weather_thunderstorm: "Tormenta", weather_thunderstorm_hail_light: "Tormenta con granizo ligero",
      weather_thunderstorm_hail_heavy: "Tormenta con granizo intenso", weather_unknown: "Clima no disponible",
      widget_weather_label: "Ahora mismo en {city}",
      widget_updated_label: "Actualizado",
      holiday_banner_template: "¡Feliz día festivo! Hoy es festivo nacional en {country}.",
      geo_consent_prompt: "¿Permitir ubicación precisa para un clima local más exacto?",
      geo_consent_note: "El sitio funciona igual sin ella — la ubicación precisa solo se usa para el clima local.",
      geo_consent_allow: "Permitir",
      geo_consent_deny: "No, gracias",
    },
    fr: {
      nav_features: "Fonctionnalités",
      nav_pricing: "Tarifs",
      nav_cta: "Commencer",
      hero_title: "Le système d'exploitation des équipes qui avancent vite",
      hero_sub: "Planifiez, automatisez et livrez ensemble — un seul espace, zéro tâche répétitive.",
      hero_note: "Sans carte bancaire · Annulez à tout moment",
      cta_primary: "Essai gratuit",
      features_title: "Tout ce dont votre équipe a besoin, au même endroit",
      feature_1_title: "Espace de travail unifié",
      feature_1_desc: "Tâches, discussions et feuilles de route au même endroit — finies les allées et venues entre cinq outils.",
      feature_2_title: "Automatisation & IA",
      feature_2_desc: "Des workflows intelligents qui apprennent votre façon de travailler et automatisent les tâches répétitives.",
      feature_3_title: "Sécurité dès la conception",
      feature_3_desc: "Contrôles alignés SOC 2 et ISO, avec accès granulaire basé sur les rôles.",
      pricing_title: "Des tarifs simples qui évoluent avec vous",
      pricing_sub: "Aucune surprise. Annulez à tout moment.",
      pricing_basic_title: "Starter",
      pricing_basic_feature1: "Jusqu'à 5 utilisateurs",
      pricing_basic_feature2: "Fonctionnalités essentielles",
      pricing_basic_feature3: "Support par e-mail",
      pricing_pro_badge: "Le plus populaire",
      pricing_pro_title: "Pro",
      pricing_pro_feature1: "Tout Starter inclus",
      pricing_pro_feature2: "Automatisation avancée",
      pricing_pro_feature3: "Support prioritaire",
      pricing_getstarted: "Commencer",
      pricing_enterprise_title: "Entreprise",
      pricing_enterprise_price: "Tarif sur mesure",
      pricing_enterprise_feature1: "Utilisateurs illimités",
      pricing_enterprise_feature2: "Chargé de compte dédié",
      pricing_enterprise_feature3: "SSO et contrats personnalisés",
      pricing_enterprise_feature4: "Support prioritaire 24/7",
      pricing_contact: "Contacter les ventes",
      footer_tagline: "Le système d'exploitation des équipes qui avancent vite.",
      footer_link_pricing: "Tarifs",
      footer_link_privacy: "Confidentialité",
      footer_link_terms: "Conditions",
      footer_link_contact: "Contact",
      footer_rights: "Tous droits réservés.",
      year: "",
      weather_clear: "Ciel dégagé", weather_mostly_clear: "Plutôt dégagé", weather_partly_cloudy: "Partiellement nuageux",
      weather_cloudy: "Nuageux", weather_fog: "Brouillard", weather_fog_rime: "Brouillard givrant",
      weather_drizzle_light: "Bruine légère", weather_drizzle_moderate: "Bruine", weather_drizzle_dense: "Bruine dense",
      weather_freezing_drizzle_light: "Bruine verglaçante légère", weather_freezing_drizzle_dense: "Bruine verglaçante",
      weather_rain_light: "Pluie légère", weather_rain_moderate: "Pluie", weather_rain_heavy: "Forte pluie",
      weather_freezing_rain_light: "Pluie verglaçante légère", weather_freezing_rain_heavy: "Pluie verglaçante",
      weather_snow_light: "Neige légère", weather_snow_moderate: "Neige", weather_snow_heavy: "Forte neige",
      weather_snow_grains: "Grains de neige", weather_rain_showers_light: "Averses légères",
      weather_rain_showers_moderate: "Averses", weather_rain_showers_violent: "Averses violentes",
      weather_snow_showers_light: "Averses de neige légères", weather_snow_showers_heavy: "Averses de neige fortes",
      weather_thunderstorm: "Orage", weather_thunderstorm_hail_light: "Orage avec grêle légère",
      weather_thunderstorm_hail_heavy: "Orage avec forte grêle", weather_unknown: "Météo indisponible",
      widget_weather_label: "En ce moment à {city}",
      widget_updated_label: "Mis à jour",
      holiday_banner_template: "Joyeuse fête ! Aujourd'hui est un jour férié en {country}.",
      geo_consent_prompt: "Autoriser la localisation précise pour une météo locale plus juste ?",
      geo_consent_note: "Le site fonctionne très bien sans — la position précise sert uniquement à la météo locale.",
      geo_consent_allow: "Autoriser",
      geo_consent_deny: "Non merci",
    },
    it: {
      nav_features: "Funzionalità",
      nav_pricing: "Prezzi",
      nav_cta: "Inizia ora",
      hero_title: "Il sistema operativo per i team che vanno veloci",
      hero_sub: "Pianifica, automatizza e realizza insieme — un solo spazio di lavoro, zero perdite di tempo.",
      hero_note: "Nessuna carta di credito richiesta · Disdici quando vuoi",
      cta_primary: "Inizia la prova gratuita",
      features_title: "Tutto ciò che serve al tuo team, in un unico posto",
      feature_1_title: "Spazio di lavoro unificato",
      feature_1_desc: "Attività, chat e roadmap in un unico spazio condiviso — basta passare da un tool all'altro.",
      feature_2_title: "Automazione & assistente AI",
      feature_2_desc: "Flussi di lavoro intelligenti imparano come lavora il tuo team e ti tolgono i compiti ripetitivi.",
      feature_3_title: "Sicuro per progettazione",
      feature_3_desc: "Controlli allineati a SOC 2 e ISO con accesso granulare basato sui ruoli — integrato, non aggiunto dopo.",
      pricing_title: "Prezzi semplici che crescono con te",
      pricing_sub: "Nessun costo a sorpresa. Disdici quando vuoi.",
      pricing_basic_title: "Starter",
      pricing_basic_feature1: "Fino a 5 utenti",
      pricing_basic_feature2: "Funzionalità principali",
      pricing_basic_feature3: "Supporto via email",
      pricing_pro_badge: "Più scelto",
      pricing_pro_title: "Pro",
      pricing_pro_feature1: "Tutto ciò che è in Starter",
      pricing_pro_feature2: "Automazione avanzata",
      pricing_pro_feature3: "Supporto prioritario",
      pricing_getstarted: "Inizia ora",
      pricing_enterprise_title: "Enterprise",
      pricing_enterprise_price: "Prezzo personalizzato",
      pricing_enterprise_feature1: "Utenti illimitati",
      pricing_enterprise_feature2: "Success manager dedicato",
      pricing_enterprise_feature3: "SSO e contratti su misura",
      pricing_enterprise_feature4: "Supporto prioritario 24/7",
      pricing_contact: "Contatta il team vendite",
      footer_tagline: "Il sistema operativo per i team che vanno veloci.",
      footer_link_pricing: "Prezzi",
      footer_link_privacy: "Privacy",
      footer_link_terms: "Termini",
      footer_link_contact: "Contatti",
      footer_rights: "Tutti i diritti riservati.",
      year: "",
      weather_clear: "Cielo sereno", weather_mostly_clear: "Prevalentemente sereno", weather_partly_cloudy: "Parzialmente nuvoloso",
      weather_cloudy: "Nuvoloso", weather_fog: "Nebbia", weather_fog_rime: "Nebbia gelata",
      weather_drizzle_light: "Pioviggine leggera", weather_drizzle_moderate: "Pioviggine", weather_drizzle_dense: "Pioviggine intensa",
      weather_freezing_drizzle_light: "Pioviggine gelata leggera", weather_freezing_drizzle_dense: "Pioviggine gelata",
      weather_rain_light: "Pioggia leggera", weather_rain_moderate: "Pioggia", weather_rain_heavy: "Pioggia intensa",
      weather_freezing_rain_light: "Pioggia gelata leggera", weather_freezing_rain_heavy: "Pioggia gelata",
      weather_snow_light: "Neve leggera", weather_snow_moderate: "Neve", weather_snow_heavy: "Neve intensa",
      weather_snow_grains: "Granuli di neve", weather_rain_showers_light: "Rovesci leggeri",
      weather_rain_showers_moderate: "Rovesci", weather_rain_showers_violent: "Rovesci violenti",
      weather_snow_showers_light: "Rovesci di neve leggeri", weather_snow_showers_heavy: "Rovesci di neve intensi",
      weather_thunderstorm: "Temporale", weather_thunderstorm_hail_light: "Temporale con grandine leggera",
      weather_thunderstorm_hail_heavy: "Temporale con grandine intensa", weather_unknown: "Meteo non disponibile",
      widget_weather_label: "In questo momento a {city}",
      widget_updated_label: "Aggiornato",
      holiday_banner_template: "Buona festa! Oggi è festività nazionale in {country}.",
      geo_consent_prompt: "Consentire la posizione precisa per un meteo locale più accurato?",
      geo_consent_note: "Il sito funziona comunque senza — la posizione precisa serve solo per il meteo locale.",
      geo_consent_allow: "Consenti",
      geo_consent_deny: "No grazie",
    },
    ro: {
      nav_features: "Funcționalități",
      nav_pricing: "Prețuri",
      nav_cta: "Începe acum",
      hero_title: "Sistemul de operare pentru echipele care se mișcă rapid",
      hero_sub: "Planifică, automatizează și livrează împreună — un singur spațiu de lucru, fără muncă inutilă.",
      hero_note: "Nu este necesar niciun card de credit · Anulează oricând",
      cta_primary: "Începe perioada de probă gratuită",
      features_title: "Tot ce are nevoie echipa ta, într-un singur loc",
      feature_1_title: "Spațiu de lucru unificat",
      feature_1_desc: "Sarcini, chat și planuri într-un singur spațiu comun — fără să mai schimbi între cinci aplicații.",
      feature_2_title: "Automatizare & asistent AI",
      feature_2_desc: "Fluxuri de lucru inteligente învață cum lucrează echipa ta și preiau sarcinile repetitive.",
      feature_3_title: "Securizat prin design",
      feature_3_desc: "Controale aliniate SOC 2 și ISO cu acces granular bazat pe roluri — integrat, nu adăugat ulterior.",
      pricing_title: "Prețuri simple care cresc odată cu tine",
      pricing_sub: "Fără taxe surpriză. Anulează oricând.",
      pricing_basic_title: "Starter",
      pricing_basic_feature1: "Până la 5 utilizatori",
      pricing_basic_feature2: "Funcționalități de bază",
      pricing_basic_feature3: "Suport prin email",
      pricing_pro_badge: "Cel mai popular",
      pricing_pro_title: "Pro",
      pricing_pro_feature1: "Tot ce include Starter",
      pricing_pro_feature2: "Automatizare avansată",
      pricing_pro_feature3: "Suport prioritar",
      pricing_getstarted: "Începe acum",
      pricing_enterprise_title: "Enterprise",
      pricing_enterprise_price: "Preț personalizat",
      pricing_enterprise_feature1: "Utilizatori nelimitați",
      pricing_enterprise_feature2: "Manager de succes dedicat",
      pricing_enterprise_feature3: "SSO și contracte personalizate",
      pricing_enterprise_feature4: "Suport prioritar 24/7",
      pricing_contact: "Contactează vânzările",
      footer_tagline: "Sistemul de operare pentru echipele care se mișcă rapid.",
      footer_link_pricing: "Prețuri",
      footer_link_privacy: "Confidențialitate",
      footer_link_terms: "Termeni",
      footer_link_contact: "Contact",
      footer_rights: "Toate drepturile rezervate.",
      year: "",
      weather_clear: "Cer senin", weather_mostly_clear: "Predominant senin", weather_partly_cloudy: "Parțial noros",
      weather_cloudy: "Noros", weather_fog: "Ceață", weather_fog_rime: "Ceață cu chiciură",
      weather_drizzle_light: "Burniță ușoară", weather_drizzle_moderate: "Burniță", weather_drizzle_dense: "Burniță deasă",
      weather_freezing_drizzle_light: "Burniță înghețată ușoară", weather_freezing_drizzle_dense: "Burniță înghețată",
      weather_rain_light: "Ploaie ușoară", weather_rain_moderate: "Ploaie", weather_rain_heavy: "Ploaie puternică",
      weather_freezing_rain_light: "Ploaie înghețată ușoară", weather_freezing_rain_heavy: "Ploaie înghețată",
      weather_snow_light: "Ninsoare ușoară", weather_snow_moderate: "Ninsoare", weather_snow_heavy: "Ninsoare puternică",
      weather_snow_grains: "Grăunțe de zăpadă", weather_rain_showers_light: "Averse ușoare",
      weather_rain_showers_moderate: "Averse", weather_rain_showers_violent: "Averse violente",
      weather_snow_showers_light: "Averse de zăpadă ușoare", weather_snow_showers_heavy: "Averse de zăpadă puternice",
      weather_thunderstorm: "Furtună", weather_thunderstorm_hail_light: "Furtună cu grindină ușoară",
      weather_thunderstorm_hail_heavy: "Furtună cu grindină puternică", weather_unknown: "Vreme indisponibilă",
      widget_weather_label: "Chiar acum în {city}",
      widget_updated_label: "Actualizat",
      holiday_banner_template: "Sărbătoare fericită! Astăzi este sărbătoare națională în {country}.",
      geo_consent_prompt: "Permiți localizarea precisă pentru o vreme locală mai exactă?",
      geo_consent_note: "Site-ul funcționează normal și fără ea — locația precisă este folosită doar pentru vremea locală.",
      geo_consent_allow: "Permite",
      geo_consent_deny: "Nu, mulțumesc",
    },
    pl: {
      nav_features: "Funkcje",
      nav_pricing: "Cennik",
      nav_cta: "Zacznij teraz",
      hero_title: "System operacyjny dla zespołów, które działają szybko",
      hero_sub: "Planuj, automatyzuj i twórz razem — jedna przestrzeń robocza, bez zbędnej pracy.",
      hero_note: "Karta kredytowa niewymagana · Anuluj w każdej chwili",
      cta_primary: "Rozpocznij darmowy okres próbny",
      features_title: "Wszystko, czego potrzebuje twój zespół, w jednym miejscu",
      feature_1_title: "Ujednolicona przestrzeń robocza",
      feature_1_desc: "Zadania, czat i plany w jednym wspólnym miejscu — koniec z przełączaniem między pięcioma narzędziami.",
      feature_2_title: "Automatyzacja i wsparcie AI",
      feature_2_desc: "Inteligentne przepływy pracy uczą się, jak działa twój zespół, i przejmują powtarzalne zadania.",
      feature_3_title: "Bezpieczeństwo w architekturze",
      feature_3_desc: "Kontrole zgodne z SOC 2 i ISO z granularnym dostępem opartym na rolach — wbudowane, nie dodane później.",
      pricing_title: "Proste ceny, które rosną razem z tobą",
      pricing_sub: "Bez ukrytych opłat. Anuluj w każdej chwili.",
      pricing_basic_title: "Starter",
      pricing_basic_feature1: "Do 5 użytkowników",
      pricing_basic_feature2: "Podstawowe funkcje",
      pricing_basic_feature3: "Wsparcie e-mail",
      pricing_pro_badge: "Najpopularniejszy",
      pricing_pro_title: "Pro",
      pricing_pro_feature1: "Wszystko z planu Starter",
      pricing_pro_feature2: "Zaawansowana automatyzacja",
      pricing_pro_feature3: "Priorytetowe wsparcie",
      pricing_getstarted: "Zacznij teraz",
      pricing_enterprise_title: "Enterprise",
      pricing_enterprise_price: "Cena indywidualna",
      pricing_enterprise_feature1: "Nieograniczona liczba użytkowników",
      pricing_enterprise_feature2: "Dedykowany opiekun klienta",
      pricing_enterprise_feature3: "SSO i umowy niestandardowe",
      pricing_enterprise_feature4: "Priorytetowe wsparcie 24/7",
      pricing_contact: "Skontaktuj się z działem sprzedaży",
      footer_tagline: "System operacyjny dla zespołów, które działają szybko.",
      footer_link_pricing: "Cennik",
      footer_link_privacy: "Prywatność",
      footer_link_terms: "Regulamin",
      footer_link_contact: "Kontakt",
      footer_rights: "Wszelkie prawa zastrzeżone.",
      year: "",
      weather_clear: "Bezchmurnie", weather_mostly_clear: "Przeważnie bezchmurnie", weather_partly_cloudy: "Częściowe zachmurzenie",
      weather_cloudy: "Pochmurno", weather_fog: "Mgła", weather_fog_rime: "Mgła szadziowa",
      weather_drizzle_light: "Lekka mżawka", weather_drizzle_moderate: "Mżawka", weather_drizzle_dense: "Gęsta mżawka",
      weather_freezing_drizzle_light: "Lekka marznąca mżawka", weather_freezing_drizzle_dense: "Marznąca mżawka",
      weather_rain_light: "Lekki deszcz", weather_rain_moderate: "Deszcz", weather_rain_heavy: "Silny deszcz",
      weather_freezing_rain_light: "Lekki marznący deszcz", weather_freezing_rain_heavy: "Marznący deszcz",
      weather_snow_light: "Lekki śnieg", weather_snow_moderate: "Śnieg", weather_snow_heavy: "Silny śnieg",
      weather_snow_grains: "Ziarna śniegu", weather_rain_showers_light: "Lekkie przelotne opady",
      weather_rain_showers_moderate: "Przelotne opady deszczu", weather_rain_showers_violent: "Gwałtowne przelotne opady",
      weather_snow_showers_light: "Lekkie przelotne opady śniegu", weather_snow_showers_heavy: "Silne przelotne opady śniegu",
      weather_thunderstorm: "Burza", weather_thunderstorm_hail_light: "Burza z lekkim gradem",
      weather_thunderstorm_hail_heavy: "Burza z silnym gradem", weather_unknown: "Pogoda niedostępna",
      widget_weather_label: "Teraz w {city}",
      widget_updated_label: "Zaktualizowano",
      holiday_banner_template: "Wesołych świąt! Dziś jest święto narodowe w {country}.",
      geo_consent_prompt: "Zezwolić na precyzyjną lokalizację dla dokładniejszej pogody lokalnej?",
      geo_consent_note: "Strona działa bez tego równie dobrze — dokładna lokalizacja służy tylko do pogody lokalnej.",
      geo_consent_allow: "Zezwól",
      geo_consent_deny: "Nie, dziękuję",
    },
    de: {
      nav_features: "Funktionen",
      nav_pricing: "Preise",
      nav_cta: "Loslegen",
      hero_title: "Das Betriebssystem für Teams, die schnell vorankommen",
      hero_sub: "Planen, automatisieren und gemeinsam liefern — ein Arbeitsbereich, keine Umwege.",
      hero_note: "Keine Kreditkarte erforderlich · Jederzeit kündbar",
      cta_primary: "Kostenlose Testversion starten",
      features_title: "Alles, was dein Team braucht, an einem Ort",
      feature_1_title: "Einheitlicher Arbeitsbereich",
      feature_1_desc: "Aufgaben, Chat und Roadmaps an einem Ort — kein Wechseln mehr zwischen fünf Tools.",
      feature_2_title: "Automatisierung & KI-Unterstützung",
      feature_2_desc: "Intelligente Workflows lernen, wie dein Team arbeitet, und übernehmen die Routineaufgaben.",
      feature_3_title: "Sicherheit von Grund auf",
      feature_3_desc: "SOC-2- und ISO-konforme Kontrollen mit granularem, rollenbasiertem Zugriff — integriert, nicht nachträglich angeflanscht.",
      pricing_title: "Einfache Preise, die mit dir wachsen",
      pricing_sub: "Keine versteckten Kosten. Jederzeit kündbar.",
      pricing_basic_title: "Starter",
      pricing_basic_feature1: "Bis zu 5 Nutzer",
      pricing_basic_feature2: "Kernfunktionen",
      pricing_basic_feature3: "E-Mail-Support",
      pricing_pro_badge: "Am beliebtesten",
      pricing_pro_title: "Pro",
      pricing_pro_feature1: "Alles aus Starter",
      pricing_pro_feature2: "Erweiterte Automatisierung",
      pricing_pro_feature3: "Priorisierter Support",
      pricing_getstarted: "Loslegen",
      pricing_enterprise_title: "Enterprise",
      pricing_enterprise_price: "Individueller Preis",
      pricing_enterprise_feature1: "Unbegrenzte Nutzer",
      pricing_enterprise_feature2: "Dedizierter Success Manager",
      pricing_enterprise_feature3: "SSO & individuelle Verträge",
      pricing_enterprise_feature4: "24/7-Prioritätssupport",
      pricing_contact: "Vertrieb kontaktieren",
      footer_tagline: "Das Betriebssystem für Teams, die schnell vorankommen.",
      footer_link_pricing: "Preise",
      footer_link_privacy: "Datenschutz",
      footer_link_terms: "AGB",
      footer_link_contact: "Kontakt",
      footer_rights: "Alle Rechte vorbehalten.",
      year: "",
      weather_clear: "Klarer Himmel", weather_mostly_clear: "Überwiegend klar", weather_partly_cloudy: "Teilweise bewölkt",
      weather_cloudy: "Bewölkt", weather_fog: "Nebel", weather_fog_rime: "Reifnebel",
      weather_drizzle_light: "Leichter Nieselregen", weather_drizzle_moderate: "Nieselregen", weather_drizzle_dense: "Starker Nieselregen",
      weather_freezing_drizzle_light: "Leichter gefrierender Nieselregen", weather_freezing_drizzle_dense: "Gefrierender Nieselregen",
      weather_rain_light: "Leichter Regen", weather_rain_moderate: "Regen", weather_rain_heavy: "Starker Regen",
      weather_freezing_rain_light: "Leichter gefrierender Regen", weather_freezing_rain_heavy: "Gefrierender Regen",
      weather_snow_light: "Leichter Schneefall", weather_snow_moderate: "Schneefall", weather_snow_heavy: "Starker Schneefall",
      weather_snow_grains: "Schneegriesel", weather_rain_showers_light: "Leichte Schauer",
      weather_rain_showers_moderate: "Schauer", weather_rain_showers_violent: "Heftige Schauer",
      weather_snow_showers_light: "Leichte Schneeschauer", weather_snow_showers_heavy: "Starke Schneeschauer",
      weather_thunderstorm: "Gewitter", weather_thunderstorm_hail_light: "Gewitter mit leichtem Hagel",
      weather_thunderstorm_hail_heavy: "Gewitter mit starkem Hagel", weather_unknown: "Wetter nicht verfügbar",
      widget_weather_label: "Gerade jetzt in {city}",
      widget_updated_label: "Aktualisiert",
      holiday_banner_template: "Frohen Feiertag! Heute ist ein gesetzlicher Feiertag in {country}.",
      geo_consent_prompt: "Präzisen Standort für genaueres lokales Wetter zulassen?",
      geo_consent_note: "Die Seite funktioniert auch ohne — der genaue Standort wird nur für das lokale Wetter verwendet.",
      geo_consent_allow: "Zulassen",
      geo_consent_deny: "Nein danke",
    }
    // Additional languages can be added here
  };
  const defaultLang = 'en';
  let currentLang = (navigator.language || navigator.userLanguage || 'en').split('-')[0];
  if (!translations[currentLang]) currentLang = defaultLang;
  let manualOverride = false;
  let langSelectEl = null;

  function localize(lang) {
    if (!translations[lang]) return;
    currentLang = lang;
    const dict = translations[lang] || translations[defaultLang];
    document.querySelectorAll('[data-i18n]').forEach(el => {
      const key = el.getAttribute('data-i18n');
      if (!key) return;
      const text = dict[key];
      if (typeof text === 'string') el.textContent = text;
    });
    // Always set year to current year
    const yearEl = document.querySelector('[data-i18n="year"]');
    if (yearEl) yearEl.textContent = new Date().getFullYear();
  }

  document.addEventListener('DOMContentLoaded', () => {
    localize(currentLang);
    langSelectEl = document.getElementById('langSelect');
    if (langSelectEl) {
      langSelectEl.value = currentLang in translations ? currentLang : 'en';
      langSelectEl.addEventListener('change', (e) => {
        manualOverride = true; // a manual pick always wins over context-based detection
        localize(e.target.value);
      });
    }
  });

  // Bridge used by integration.js (Phase 3 context wiring). A manual language
  // pick always wins — this only applies the detected language pre-emptively.
  window.NovaSphereI18n = {
    localize,
    getCurrentLang: () => currentLang,
    getDict: (lang) => translations[lang] || translations[defaultLang],
    isManualOverride: () => manualOverride,
    setLanguageFromContext(lang) {
      if (manualOverride || !translations[lang]) return false;
      localize(lang);
      if (langSelectEl) langSelectEl.value = lang;
      return true;
    },
  };
})();
